site_name: BomberIF
docs_dir: doc
use_directory_urls: false

theme:
  name: material
  palette:
    scheme: slate
    primary: deep purple
    accent: cyan
  features:
    - search.suggest
    - search.highlight

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences

nav:
  - Início: doc_bomberIF.md